import type { Metadata } from "next";
import { EB_Garamond, DM_Sans, DM_Mono } from "next/font/google";
import "../css/globals.css";
import Footer from "@/components/Footer";

const fontSerif = EB_Garamond({
  variable: "--font-serif-loaded",
  subsets: ["latin"],
});

const fontSans = DM_Sans({
  variable: "--font-sans-loaded",
  subsets: ["latin"],
});

const fontMono = DM_Mono({
  variable: "--font-mono-loaded",
  weight: ["400", "500"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${fontSerif.variable} ${fontSans.variable} ${fontMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
